name: Test Github Action workflo_dispatch

on:
  workflow_dispatch: # This is required for manual triggering
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev

jobs:
  merge-dev-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
